import About from "@/components/About";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Projects from "@/components/Projects";
import Skills from "@/components/Skills";
import Work from "@/components/Work";
import Head from "next/head";
import Image from "next/image";
import codingImage from "../../public/programming.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Neeraj | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col ">
        {/* Header Section */}
        <Navbar />
        {/* Home Section */}
        <div className="flex  md:gap-5 md:px-44 md:py-12 mt-10 md:mt-6">
          <div>
            <div className="w-5 h-5 bg-indigo-700 rounded-full mt-3"></div>
            <div className="h-72 bg-gradient-to-b from-indigo-700 via-indigo-600 to-purple-200 w-1 ml-2 mb-0.5"></div>
          </div>
          <div className="flex flex-col items-center md:items-start  font-sans gap-4 ">
            <h1 className="text-6xl ml-7 md:ml-0">
              Hi, i'm <span className="text-indigo-700 font-bold"> Neeraj</span>
            </h1>
            <h2 className="w-72 text-2xl">
              I develop ,user intefaces and Web applications
            </h2>
            <div className="p-3  shadow-md">
              <Image
                className=" object-cover h-[28rem] w-[55rem] rounded-md "
                src={codingImage}
                alt={"image of coding"}
              />
            </div>
          </div>
        </div>
        {/* About Section */}
        <div id="about" className=" px-5 py-5 md:px-44 md:py-12 ">
          <About />
        </div>
        {/* Skills Section */}
        <div className=" px-5 py-5 md:px-44 md:py-12 ">
          <Skills />
        </div>
        {/* Work Section */}
        <div className="px-5 py-5 md:px-44 md:py-12 ">
          <Work />
        </div>
        {/* Projects Section */}
        <div className="px-5 py-5 md:px-44 md:py-12 ">
          <Projects />
        </div>
        {/* Contact Section */}
        <div className="px-5 py-5 md:px-44 md:py-12 ">
          <Contact />
        </div>
        {/* Footer Section */}
        <div className="">
          <Footer />
        </div>
      </div>
    </>
  );
}
